name: Tests

on: [push, pull_request, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .github/workflows
        
    steps:      
    - uses: actions/checkout@v2
      
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.1.4
    
    - name: Install Node dependencies
      run: yarn install
      
    - name: Run Tests
      run: yarn test
